### ISSUE TITLE
cg-comp did not complete

### ISSUE THREAD

**Issue by OlaFosheimGrostad** [apertium/apertium-nob#2]
The problem was caused by using vislcg3 @1.3.7_4, it was fixed by installing cg3 from github. Maybe set the requirements to a higher version.

**Comment by unhammer** [comment]
we normally just bump those for releases, expecting git users to use nightly packages (see https://wiki.apertium.org/wiki/Install_Apertium_core_using_packaging ), but doesn't hurt to do it a few more times

closed in a9bb819
